#:kivy 1.0.9

# The middle line
<PongGame>:
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0
            size: 20, self.height

# Left Side Label
    Label:
        font_size: 70
        center_x: root.width / 4
        top: root.top - 50
        text: "0"
# Right Side Label
    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: "0"